TRAVIS add Python 3 build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,24 +1,25 @@
+sudo: required
+
 language: python
 
-python:
-    - "2.7"
+env:
+  matrix:
+    - DISTRIB="neurodebian" COVERAGE="true"
+    - DISTRIB="conda" PYTHON_VERSION="3.5" NUMPY_VERSION="*" SCIPY_VERSION="*"
+      SCIKIT_LEARN_VERSION="*" PANDAS_VERSION="*" MATPLOTLIB_VERSION="*"
+      NETWORKX_VERSION="*"
 
 virtualenv:
   system_site_packages: true
 
-before_install:
-    - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
-    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn python-pandas python-networkx python-nipype
-    - sudo apt-get install -qq python-pip
-    - pip install "nilearn>=0.1.3"
-    - pip install coverage coveralls
-
-install:
-    - python setup.py install
+install: source continuous_integration/install.sh
 
 script:
     - make clean
     - make test-code
 
 after_success:
-    - coveralls
+    - |
+      if [[ "$COVERAGE" == "true" ]]; then
+          coveralls || echo "coverage upload failed"
+      fi
